services:
  app:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    restart: always
    ports: [] # Disable public port for production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
